### ISSUE TITLE
iTerm support

### ISSUE THREAD

**Issue by taufikobet** [sathya-me/OpenInTerminal#1]
Is it possible to open in iTerm.app instead of Terminal.app?

**Comment by tuchangwei** [comment]
I also want to develop the kind Plug-in :)
Thank you.

**Comment by sathya-me** [comment]
I have created a separate project under the name "Open in iTerm" (https://github.com/sathya-me/Open-In-iTerm) to open the app in 'iTerm' and use terminal as backup and sent the pull request to 'alcatraz'. (https://github.com/supermarin/alcatraz-packages/pull/353). Hope it will be helpful once they accept it.

Thanks.
